---
- name: Converge
  hosts: all
  vars:
    ignore_systemd_error: true
    node_exporter_version: 2.4.2
  roles:
    - role: ansible-node_exporter-role

- name: Converge
  hosts: all
  vars:
    ignore_systemd_error: true
    node_exporter_version: 2.4.3
    node_exporter_checksum: sha256:3aa063498ab3b4d1bee103d80098ba33d02b3fed63cb46e47e1d16290356db8a
  roles:
    - role: ansible-node_exporter-role
