#!/bin/bash

#URL=https://github.com/node_exporter/node_exporter/releases/download/v2.5.0-rc.2/sha256sums.txt
BASE_URL=https://github.com/prometheus/node_exporter/releases/download

ME=$0
CUR_DIR=$(dirname $(readlink -f $ME))
PROJECT_ROOT=$(dirname ${CUR_DIR})

tags=$(curl https://api.github.com/repos/prometheus/node_exporter/git/refs/tags | awk '/"ref"/')

VERSIONS=(
    v0.18.1
    v0.18.0
    v0.17.0
    v0.16.0
    v0.15.2
    v0.15.1
    v0.15.0
    )

for version in ${VERSIONS[@]}; do
    dest=${PROJECT_ROOT}/vars/versions/$version.sha256sums.yml
    echo --- > $dest
    curl -L $BASE_URL/${version}/sha256sums.txt | sed -r 's/(\S+)\s+(\S+)/\2: sha256:\1/' >> $dest
done
